### PR TITLE
Change screenshots to animated GIFs

### PR DESCRIPTION
**Pull request by jasonlfunk**
Change the screenshots to animated gifs to give a better feel for how the formatters work.

### CODE REVIEW

**Comment by whatthejeff** [comment]
:+1: Thanks!

**Comment by mdavis1982** [comment]
:+1: I like this a lot!

@whatthejeff The screenshots were originally in the screenshots branch. Would it make sense to move the new animated GIFs to there so that they're not in the main repository? And if not, should we delete the screenshots branch?

**Comment by jasonlfunk** [comment]
It might be good to do that and move the links from the readme to your repo. Right now the URLs are pointed at my fork.

**Comment by mdavis1982** [comment]
@whatthejeff moved the screenshots into the repository and updated the links so that they weren't pointing at your fork any more :smile: 

I don't mind them being in the main branch, just as long as we remove the screenshots branch if it's no longer needed.

**Comment by whatthejeff** [comment]
Yeah, let's get rid of the screenshots branch. I think it's pretty typical that these types of images are in the main branch.

**Pull request merged**
